Replace strings left/right double quotation by '"'
When making copy and paste of some examples I was getting this kind of errors:
```
Error: unexpected � in file arithRec.dl at line 12
C(“a”). C(“b”). C(“c”). C(“d”).
--^---------------------------------------------
Error: unexpected � in file arithRec.dl at line 12
C(“a”). C(“b”). C(“c”). C(“d”).
---^--------------------------------------------
Error: unexpected � in file arithRec.dl at line 12
C(“a”). C(“b”). C(“c”). C(“d”).
----^-------------------------------------------
```
Due to use of left/right double quotation (unicode) instead of the ASCII quotation mark.
Probably the same should be done in other places.